import {FormEvent,useEffect,useState} from 'react';
import {CircleCheck,ImagePlus,Plus,Save,Trash2} from 'lucide-react';
import {api,apiForm} from './api';

export type PaymentMethod={id:string;label:string;active:boolean};
export type InvoiceDefaults={companyName:string;tagline:string;phone:string;address:string;thankYouTitle:string;footerNote:string;companySignatureUrl:string};
export type CheckoutConfig={taxRate:number;taxEnabledByDefault:boolean;paymentMethods:PaymentMethod[];invoiceDefaults:InvoiceDefaults};

export default function CheckoutSettings(){
  const[config,setConfig]=useState<CheckoutConfig|null>(null);const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);
  useEffect(()=>{api<CheckoutConfig>('/api/checkout-settings').then(setConfig).catch(error=>setMessage((error as Error).message))},[]);
  const updateMethod=(index:number,patch:Partial<PaymentMethod>)=>setConfig(current=>current?{...current,paymentMethods:current.paymentMethods.map((method,i)=>i===index?{...method,...patch}:method)}:current);
  const updateInvoice=(patch:Partial<InvoiceDefaults>)=>setConfig(current=>current?{...current,invoiceDefaults:{...current.invoiceDefaults,...patch}}:current);
  const uploadSignature=async(file?:File)=>{if(!file)return;setSaving(true);setMessage('');try{const body=new FormData();body.append('image',file);const result=await apiForm<{url:string}>('/api/invoice-assets',body);updateInvoice({companySignatureUrl:result.url});setMessage('Signature importée. Enregistrez la configuration pour l’utiliser par défaut.')}catch(error){setMessage((error as Error).message)}finally{setSaving(false)}};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!config)return;setSaving(true);setMessage('');try{setConfig(await api<CheckoutConfig>('/api/checkout-settings',{method:'PUT',body:JSON.stringify(config)}));setMessage('Configuration enregistrée. Elle est déjà active dans la caisse.')}catch(error){setMessage((error as Error).message)}finally{setSaving(false)}};
  if(!config)return <div className="loading"><i/><span>Chargement des paramètres…</span></div>;
  return <form className="checkout-settings panel" onSubmit={submit}>
    <header><div><h2>Configuration de la caisse</h2><p>Ces choix sont appliqués automatiquement à chaque nouvelle vente.</p></div><button className="primary compact" disabled={saving}><Save/>{saving?'Enregistrement…':'Enregistrer'}</button></header>
    {message&&<div className={message.startsWith('Configuration')||message.startsWith('Signature')?'success':'error'}>{message}</div>}
    <section className="settings-section"><div><h3>TVA</h3><p>Définissez le taux utilisé et si la TVA doit être cochée par défaut.</p></div><div className="settings-fields"><label>Taux de TVA (%)<input type="number" min="0" max="100" step="0.01" value={config.taxRate} onChange={event=>setConfig({...config,taxRate:Number(event.target.value)})}/></label><label className="setting-switch"><input type="checkbox" checked={config.taxEnabledByDefault} onChange={event=>setConfig({...config,taxEnabledByDefault:event.target.checked})}/><span><b>TVA activée par défaut</b><small>Le vendeur pourra toujours la désactiver pour une vente.</small></span></label></div></section>
    <section className="settings-section invoice-default-settings"><div><h3>Modèle de facture</h3><p>Ces informations sont copiées dans chaque nouvelle facture. Elles restent ensuite modifiables individuellement.</p></div><div className="invoice-default-fields"><label>Nom de l’entreprise<input value={config.invoiceDefaults.companyName} onChange={event=>updateInvoice({companyName:event.target.value})}/></label><label>Slogan<input value={config.invoiceDefaults.tagline} onChange={event=>updateInvoice({tagline:event.target.value})}/></label><label>Téléphone<input value={config.invoiceDefaults.phone} onChange={event=>updateInvoice({phone:event.target.value})}/></label><label>Adresse<input value={config.invoiceDefaults.address} onChange={event=>updateInvoice({address:event.target.value})}/></label><label>Titre du message<input value={config.invoiceDefaults.thankYouTitle} onChange={event=>updateInvoice({thankYouTitle:event.target.value})}/></label><label className="field-wide">Texte par défaut<textarea rows={3} value={config.invoiceDefaults.footerNote} onChange={event=>updateInvoice({footerNote:event.target.value})}/></label><div className="default-signature"><span>Signature de l’entreprise</span>{config.invoiceDefaults.companySignatureUrl?<img src={config.invoiceDefaults.companySignatureUrl} alt="Signature par défaut"/>:<small>Aucune signature enregistrée</small>}<label><ImagePlus/>Importer un PNG ou JPG<input type="file" accept="image/png,image/jpeg" onChange={event=>{void uploadSignature(event.target.files?.[0]);event.target.value=''}}/></label>{config.invoiceDefaults.companySignatureUrl&&<button type="button" onClick={()=>updateInvoice({companySignatureUrl:''})}>Retirer</button>}</div></div></section>
    <section className="settings-section payment-settings"><div><h3>Moyens de paiement</h3><p>Activez uniquement les méthodes proposées au vendeur.</p></div><div className="payment-method-list">{config.paymentMethods.map((method,index)=><div className={method.active?'enabled':''} key={`${method.id}-${index}`}><label className="method-toggle"><input type="checkbox" checked={method.active} onChange={event=>updateMethod(index,{active:event.target.checked})}/><CircleCheck/></label><label>Nom affiché<input value={method.label} onChange={event=>updateMethod(index,{label:event.target.value})}/></label><label>Identifiant<input value={method.id} onChange={event=>updateMethod(index,{id:event.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'_')})}/></label><button type="button" className="icon danger" title="Supprimer" onClick={()=>setConfig({...config,paymentMethods:config.paymentMethods.filter((_,i)=>i!==index)})}><Trash2/></button></div>)}<button type="button" className="add-method" onClick={()=>setConfig({...config,paymentMethods:[...config.paymentMethods,{id:`method_${config.paymentMethods.length+1}`,label:'Nouveau moyen',active:true}]})}><Plus/>Ajouter un moyen de paiement</button></div></section>
  </form>;
}
